# ==Tidy-Viewer Config Example==
# Remove the first column of comments for valid toml file
# All fields must be defined. Partial files will not be read.
# The delimiter separating the columns. [default: ,]
delimiter = ","
# Add a title to your tv. Example 'Test Data' [default: NA ("")]
title = ""
# Add a footer to your tv. Example 'footer info' [default: NA ("")]
footer = ""
# The upper (maximum) width of columns. [default: 20]
upper_column_width = 20
# The minimum width of columns. Must be 2 or larger. [default: 2]
lower_column_width = 2
# head number of rows to output <row-display> [default: 25]
number = 10
# extend width and length in terms of the number of rows and columns displayed beyond term width [default: false]
extend_width_and_length = false
# meta_color = [R,G,B] color for row index and "tv dim: rows x cols"
meta_color = [64, 179, 162]
# header_color = [R,G,B] color for column headers
header_color = [232, 168, 124]
# std_color = [R,G,B] color for standard cell data values
std_color = [133, 205, 202]
# na_color = [R,G,B] color for NA values
na_color = [226, 125, 95]
# neg_num_color = [R,G,B] color for negative values
neg_num_color = [226, 125, 95]
